name: CI
on: push
jobs:
  make:
    runs-on: ubuntu-latest
    container: psl1ght/psl1ght:latest
    steps:
      - run: |
          git clone https://github.com/nandolawson/Pimp-My-XMB
        name: Get repo
      - run: |
          cd Pimp-My-XMB && sh make.sh
        name: Generate aso
