name: CI
on: push
jobs:
  make:
    runs-on: ubuntu-latest
    container: psl1ght/psl1ght:latest
    steps:
      - run: |
          git clone https://github.com/nandolawson/Pimp-My-XMB
          uname -a
        name: Prepare
      - run: |
          cd Pimp-My-XMB
          export PS3DEV=/usr/local/ps3dev
          export PSL1GHT=$PS3DEV
          export PATH=$PATH:$PS3DEV/bin
          export PATH=$PATH:$PS3DEV/ppu/bin
          export PATH=$PATH:$PS3DEV/spu/bin
          sh make.sh
        name: Generate aso
